### PR TITLE
feat - cogs management and more resources command

### PR DESCRIPTION
**Pull request by 0xMukesh**
#1 
I have created the cogs management system 

The file structure of the `cogs` folder is something like this:
image

I have also added more resources command for other languages (JS, C++) and frameworks (ReactJS)

Change the `automeme` channel ID while testing the bot 😄

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Thanks for your contribution @Kira272921 ,
but some changes are needed in the [help command](https://github.com/Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot/pull/2/files#diff-7239ceb7192b216fca002fc7489fe517646b6d321314bd8665425876ed65b75bR11), instructions are provided in Discord.

**Comment by 0xMukesh** [comment]
@EFFLUX110 I have improved the help command embed and it looks like this right now: 
image
image
image
image

**Comment by Mrinank-Bhowmick** [comment]
> @EFFLUX110 I have improved the help command embed and it looks like this right now: 
> image
> image
> image
> image
> 

Thanks for your contribution @Kira272921 🎊

**Comment by Mrinank-Bhowmick** [comment]
@all-contributors please add @Kira272921 for code contribution

**Comment by Mrinank-Bhowmick** [comment]
@all-contributors please add @Kira272921 for code contribution

**Comment by adityamangal1** [comment]
Great work @Kira272921 🎉

**Comment by 0xMukesh** [comment]
> Great work @Kira272921 🎉

Thanks!

**Pull request merged**
