### PR TITLE
Added GitHub search and info commands and error handler

### PR DESCRIPTION
**Pull request by 0xMukesh**
I have added these new commands 
- GitHub search repo - Searches for a repo 
> **Preview**

image

- GitHub search user - Searches for a user  
> **Preview**

image

> **There is a bug with the paginator, I have reported to the `discordSuperUtils` dev team, I will create a new PR as soon as the bug is fixed 😄**

- GitHub info repo - Sends the info about the repo 
> **Preview**

image

- GitHub info user - Sends the info about a user 
> **Preview**

image

### CODE REVIEW

**Comment by 0xMukesh** [comment]
Sorry for not mentioning what the bug is beforehand 
> The bug is with `discordSuperUtils.generate_embeds()` which creates an extra embed page at the end.
> For example, if we are using `%gs_r 10 discord bot` command, this gives us 10 search results for `discord bot`.
> Each embed page will have `5` search results contained in them, so by this there should be total only `2` embed pages, but as I said there is an extra embed page been generated at the ended which results to total 3 embed pages

**Comment by Mrinank-Bhowmick** [comment]
@Kira272921 great work ,thanks for the contribution 😊

**Comment by EFFLUX110** [comment]
#6 solved

**Comment by Mrinank-Bhowmick** [comment]
#5 solved

**Pull request merged**
